language: cpp
dist: trusty
sudo: false

env:
  global:
    - VERSION=18.04

matrix:
  include:
    - env: PY_MAJOR_VER=2
    - env: PY_MAJOR_VER=3

install:
  - wget -c --no-check-certificate https://repo.continuum.io/miniconda/Miniconda${PY_MAJOR_VER}-latest-Linux-x86_64.sh -P /tmp
  - bash /tmp/Miniconda${PY_MAJOR_VER}-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - PATH="$HOME/miniconda/bin:$PATH" conda install -y constructor

script:
  - sed "s|@PY_MAJOR_VER@|${PY_MAJOR_VER}|g" construct.yaml.in > construct.yaml
  - PATH="$HOME/miniconda/bin:$PATH" constructor .
  - bash otconda*.sh -b -p $HOME/otconda
  - PATH="$HOME/otconda/bin:$PATH" python otconda_test.py

deploy:
  provider: releases
  api_key:
    secure: OCZ+GaG/yom2wLOkAV9j4xIUXSaXPgKzDVvups1FiQ6AopFRZAA3gtBGuO1v4mfN0Jl8Lpc7ZTkvCWsez5TJIXt6q9cwcMuyDrcryEtnK+cmyT02nABnDE21DdbO9dwF5PXrIirdYLrDcXD7wcg/GwDuPV3vISbJ5o2OFyT92xHpPhykRndfSRW7vnLScYx9lPZgAyYgKd8zGHNarLCPrng/b96LKoKNzRTn2BVuJv2982Lzk5lJWq7ilnOHifJTFDQHf5Lx+R9lAugr6rzbFOObc236uZZxPMpzivD7E+yhD+Z7O19VmOlVWpiU4q8H110BzLIRWNKEfIyIdfySY/1oZjBmUI3wkHrRZ0TNkMTzW8aFjuGD8CUkxljZWOLKzmzB5eKFG15U7ZPtraHsOB+Q3yW03aEaFYKVGR4H5lghaAee/7p3kjlSFGtD0NWrBDiS/G0vLNzmTuexSvxmPUSyJ1NKZx9erWHgjBJTESdN58iiq7+QYdil9elA0KJe3MlM1k4BLPU4EqNpP8fS11puWYwXQwD+SFDksEO0U8AvNEPP0IzOPUAryRZ4J54risaKoEj7L/7DlJj4O6D9C4rCTLURzDL9qQqByt7eULKkfOm5rnhCHv1t3a6mhkkycKqXpj0stVe/FzfaQyoTwthrXxvhTqnxo5HS9ZA6dU8=
  file: otconda${PY_MAJOR_VER}-${VERSION}-Linux-x86_64.sh
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: openturns/otconda
