environment:
  VERSION: 1.12
  matrix:
    - PY_MAJOR_VER: 2
    - PY_MAJOR_VER: 3

install:
  - curl -fSsLO https://repo.anaconda.com/miniconda/Miniconda%PY_MAJOR_VER%-latest-Windows-x86_64.exe
  - Miniconda%PY_MAJOR_VER%-latest-Windows-x86_64.exe /InstallationType=JustMe /S /D=C:\miniconda64
  - set CONDA_ROOT="C:\miniconda64"
  - set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%
  - set PATH=C:\msys64\usr\bin;%PATH%
  - python -c "import sys; print(sys.version, sys.executable)"
  #- conda config --add channels conda-forge
  - conda install -y constructor

  # https://github.com/ContinuumIO/anaconda-issues/issues/10549
  - conda install -y xz zstd

  # else fails on py3.7 ???
  - xcopy /s %CONDA_ROOT%\Library\bin\tiff.dll %CONDA_ROOT%\Lib\site-packages\PIL
  - xcopy /s %CONDA_ROOT%\Library\bin\zlib.dll %CONDA_ROOT%\Lib\site-packages\PIL
  - xcopy /s %CONDA_ROOT%\Library\bin\liblzma.dll %CONDA_ROOT%\Lib\site-packages\PIL
  - xcopy /s %CONDA_ROOT%\Library\bin\libzstd.dll %CONDA_ROOT%\Lib\site-packages\PIL

build_script:
  - sed "s/@PY_MAJOR_VER@/%PY_MAJOR_VER%/g" construct.yaml.in > construct.yaml
  - constructor -v .
  - otconda%PY_MAJOR_VER%-%VERSION%-Windows-x86_64.exe /S /D=C:\otconda
  - set CONDA_ROOT="C:\otconda"
  - set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%
  - python otconda_test.py

artifacts:
  - path: otconda*.exe
    name: binary

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Windows installer'
  provider: GitHub
  auth_token:
    secure: 4CkqK7ssPZsVuYY4gnYun8TlaVakivCHyw+EnT6z/KdoG3iTDcebHNdHQ+cYJFt+
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: /v.*/
    appveyor_repo_tag: true
